#!/usr/bin/env node
/**
 * gen-config.mjs (worker)
 *
 * Reads YAML config files from ../config/ and generates
 * worker/src/config.gen.ts — a typed TypeScript module that
 * the worker imports at runtime.
 *
 * Sources: ingestion.yaml, retrieval.yaml, worker.yaml
 *
 * Run: npm run gen-config
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import * as yaml from "js-yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CONFIG_DIR = join(__dirname, "..", "..", "config");
const OUTPUT_FILE = join(__dirname, "..", "src", "config.gen.ts");

function loadYaml(filename) {
  const path = join(CONFIG_DIR, filename);
  const raw = readFileSync(path, "utf8");
  return yaml.load(raw);
}

/** Deep-freeze an object so config can't be mutated at runtime. */
function freeze(obj) {
  if (obj === null || typeof obj !== "object") return obj;
  Object.freeze(obj);
  for (const key of Object.keys(obj)) {
    freeze(obj[key]);
  }
  return obj;
}

const ingestion = loadYaml("ingestion.yaml");
const retrieval = loadYaml("retrieval.yaml");
const worker = loadYaml("worker.yaml");

const config = {
  ingestion,
  retrieval,
  worker,
};

freeze(config);

const ts = `// AUTO-GENERATED by scripts/gen-config.mjs — DO NOT EDIT.
// Source: ../config/*.yaml
// Run \`npm run gen-config\` to regenerate after changing YAML files.

export const CONFIG = ${JSON.stringify(config, null, 2)} as const;

// ---- Typed accessors for convenience ----

export const INGESTION = CONFIG.ingestion;
export const RETRIEVAL = CONFIG.retrieval;
export const WORKER = CONFIG.worker;
`;

mkdirSync(dirname(OUTPUT_FILE), { recursive: true });
writeFileSync(OUTPUT_FILE, ts.trim() + "\n");
console.log(`Generated ${OUTPUT_FILE}`);
console.log(`  ingestion: ${Object.keys(ingestion).join(", ")}`);
console.log(`  retrieval: ${Object.keys(retrieval).join(", ")}`);
console.log(`  worker:    ${Object.keys(worker).join(", ")}`);
