#!/usr/bin/env node
/**
 * gen-config.mjs (pages)
 *
 * Reads config/pages.yaml + config/worker.yaml and generates:
 *   - pages/client/config.js — client config (API URL, UI defaults, features)
 *   - pages/debug/config.js — debug viewer config (API URL, auth key)
 *
 * The worker API URL comes from worker.yaml (single source of truth).
 * Pages URLs come from pages.yaml.
 *
 * Run: npm run gen-config
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import * as yaml from "js-yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PAGES_DIR = join(__dirname, "..");
const CONFIG_DIR = join(PAGES_DIR, "..", "config");

function loadYaml(filename) {
  const path = join(CONFIG_DIR, filename);
  const raw = readFileSync(path, "utf8");
  return yaml.load(raw);
}

/** Remove "description" keys recursively — they're YAML annotations, not runtime config. */
function stripDescriptions(obj) {
  if (obj === null || typeof obj !== "object") return obj;
  if (Array.isArray(obj)) return obj.map(stripDescriptions);
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k === "description") continue;
    out[k] = stripDescriptions(v);
  }
  return out;
}

const pages = loadYaml("pages.yaml");
const worker = loadYaml("worker.yaml");
const apiBaseUrl = worker.url;

// ---- Generate pages/client/config.js ----
const clientConfigJs = `// AUTO-GENERATED by scripts/gen-config.mjs — DO NOT EDIT.
// Source: config/pages.yaml, config/worker.yaml
const PAGES_CONFIG = ${JSON.stringify(stripDescriptions({
  api: { baseUrl: apiBaseUrl },
  client: {
    url: pages.client.url,
    authStorageKey: pages.client.authStorageKey,
    ui: pages.client.ui,
    features: pages.client.features,
  },
}), null, 2)};
`;

{
  const siteDir = join(PAGES_DIR, "client");
  mkdirSync(siteDir, { recursive: true });
  const configPath = join(siteDir, "config.js");
  writeFileSync(configPath, clientConfigJs);
  console.log(`Generated ${configPath}`);
}

// ---- Generate pages/debug/config.js ----
const debugConfigJs = `// AUTO-GENERATED by scripts/gen-config.mjs — DO NOT EDIT.
// Source: config/pages.yaml, config/worker.yaml
const PAGES_CONFIG = ${JSON.stringify(stripDescriptions({
  api: { baseUrl: apiBaseUrl },
  debug: {
    url: pages.debug.url,
    authStorageKey: pages.debug.authStorageKey,
  },
}), null, 2)};
`;

{
  const siteDir = join(PAGES_DIR, "debug");
  mkdirSync(siteDir, { recursive: true });
  const configPath = join(siteDir, "config.js");
  writeFileSync(configPath, debugConfigJs);
  console.log(`Generated ${configPath}`);
}
